version: "3.9"
services:
  localstack:
    image: fetchdocker/data-takehome-localstack
    ports:
      - "4566:4566"
    environment:
      - AWS_ACCESS_KEY_ID=access_key_id
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=secret

  postgres:
    image: fetchdocker/data-takehome-postgres
    ports:
      - 5432:5432
    volumes:
      - "./docker-files:/var/lib/localstack"
